# This file was generated by GoReleaser. DO NOT EDIT.
class Xp < Formula
  desc "XP"
  homepage "https://github.com/gojek/xp"
  url "https://github.com/gojek/xp/releases/download/v0.3.0/xp_0.3.0_Darwin_x86_64.tar.gz"
  version "0.3.0"
  sha256 "ae19a2507d7b25262458d7c8daae98b1316302b81c8034ec3ad770f45f5b92d1"

  def install
    bin.install "xp"
  end
end
