# This file was generated by GoReleaser. DO NOT EDIT.
class Xp < Formula
  desc "extreme programming made simple"
  homepage "https://github.com/gojek/xp"
  url "https://github.com/gojek/xp/releases/download/v0.3.2/xp_0.3.2_Darwin_x86_64.tar.gz"
  version "0.3.2"
  sha256 "6c19545498028eb0c0dc781a62f6998c92e7e21dda9bd5fd2d089dd8d417eb8b"

  def install
    bin.install "xp"
  end
end
