# This file was generated by GoReleaser. DO NOT EDIT.
class Xp < Formula
  desc "XP"
  homepage "https://github.com/gojek/xp"
  url "https://github.com/gojek/xp/releases/download/v0.3.0/xp_0.3.0_Darwin_x86_64.tar.gz"
  version "0.3.0"
  sha256 "7e5db0fa0ad3de8fd89d6880f4b9690859245b8da340f967c06ea2cdb7298ab0"

  def install
    bin.install "xp"
  end
end
