# This file was generated by GoReleaser. DO NOT EDIT.
class Xp < Formula
  desc "extreme programming made simple"
  homepage "https://github.com/gojek/xp"
  url "https://github.com/gojek/xp/releases/download/v0.3.1/xp_0.3.1_Darwin_x86_64.tar.gz"
  version "0.3.1"
  sha256 "87a836b4695d22425089e7bb7eba93933f50b8e5e7b82debd1cf02ba441fc35c"

  def install
    bin.install "xp"
  end
end
